# NOTEBOOK 00.1: *EVENTOS MEJORADO*

In [1]:
import pandas as pd 
import numpy as np

Cargamos un df realizado en excel tras investigar:
- Festivos nacionales de EEUU
- Grandes eventos
- Fiestas más importantes de las principales comunidades representadas en las tres ciudades estudiadas:
  - Judía
  - Musulmana
  - Budista
  - China

In [2]:
df = pd.read_csv('data/eventos_extra_raw.csv')

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Fecha           120 non-null    object
 1   Nombre festivo  120 non-null    object
 2   Grupo           120 non-null    object
 3   Descripción     120 non-null    object
dtypes: object(4)
memory usage: 3.9+ KB

In [4]:
df['Fecha'] = pd.to_datetime(df['Fecha'], format= "%d/%m/%Y")

In [5]:
df.head(25)

,Fecha,Nombre festivo,Grupo,Descripción
0,2011-01-01,Año Nuevo,Nacional,Celebración del primer día del año según el ca...
1,2011-07-04,Día de la Independencia,Nacional,Conmemoración de la independencia de EE.UU. en...
2,2011-11-11,Día de los Veteranos,Nacional,Honra a los veteranos de las Fuerzas Armadas d...
3,2011-12-25,Navidad,Nacional,Fiesta cristiana que celebra el nacimiento de ...
4,2011-03-17,Día de San Patricio,Nacional,"Fiesta en honor a San Patricio, patrón de Irla..."
5,2011-06-19,Juneteenth,Nacional,Conmemoración del fin de la esclavitud en EE.U...
6,2011-01-17,Día de Martin Luther King Jr.,Nacional,Honra al líder de los derechos civiles Martin ...
7,2011-02-21,Día de los Presidentes,Nacional,Reconocimiento a todos los presidentes de EE.UU.
8,2011-04-18,Día de los Caídos,Nacional,Honra a los militares estadounidenses fallecid...
9,2011-09-05,Día del Trabajo,Nacional,Reconocimiento a los trabajadores y sus contri...
10,2011-10-10,Día de Colón,Nacional,Conmemoración de la llegada de Cristóbal Colón...
11,2011-11-24,Día de Acción de Gracias,Nacional,Día de agradecimiento por la cosecha y bendici...
12,2011-09-29,Rosh Hashaná,Judaísmo,"Año Nuevo judío, marcado por oración y reflexión."
13,2011-10-08,Yom Kipur,Judaísmo,"Día del Perdón en el judaísmo, dedicado al ayu..."
14,2011-08-01,Ramadán,Islam,Mes sagrado de ayuno y oración para los musulm...
15,2011-08-30,Eid al-Fitr,Islam,Fiesta que marca el fin del Ramadán en el islam.
16,2011-10-26,Diwali,Hinduismo,"Festival hindú de las luces, que simboliza la ..."
17,2011-05-17,Vesak,Budismo,"Celebración budista del nacimiento, iluminació..."
18,2012-01-01,Año Nuevo,Nacional,Celebración del primer día del año según el ca...
19,2012-07-04,Día de la Independencia,Nacional,Conmemoración de la independencia de EE.UU. en...
20,2012-11-11,Día de los Veteranos,Nacional,Honra a los veteranos de las Fuerzas Armadas d...
21,2012-12-25,Navidad,Nacional,Fiesta cristiana que celebra el nacimiento de ...
22,2012-03-17,Día de San Patricio,Nacional,"Fiesta en honor a San Patricio, patrón de Irla..."
23,2012-06-19,Juneteenth,Nacional,Conmemoración del fin de la esclavitud en EE.U...
24,2012-01-16,Día de Martin Luther King Jr.,Nacional,Honra al líder de los derechos civiles Martin ...

In [6]:
df['Nombre festivo'].value_counts()

Nombre festivo
Año Nuevo                        6
Día de la Independencia          6
Día de los Veteranos             6
Navidad                          6
Día de San Patricio              6
Juneteenth                       6
Día de Martin Luther King Jr.    6
Día de los Presidentes           6
Día de los Caídos                6
Día del Trabajo                  6
Día de Colón                     6
Día de Acción de Gracias         6
Rosh Hashaná                     6
Yom Kipur                        6
Ramadán                          6
Eid al-Fitr                      6
Diwali                           6
Vesak                            6
Superbowl                        6
Año Nuevo Chino                  6
Name: count, dtype: int64

In [7]:
df = df.sort_values(by='Fecha')
df.reset_index(drop= True, inplace= True)

In [8]:
nombres_nuevos = {
    'Año Nuevo': 'NewYear',
    'Día de Martin Luther King Jr.': 'MartinLutherKing',
    'Año Nuevo Chino': 'ChineeseNewYear',
    'Superbowl': 'Superbowl',
    'Día de los Presidentes': 'President',
    'Día de San Patricio': 'StPatrick',
    'Día de los Caídos': 'Memorial',
    'Vesak': 'Buddhist',
    'Juneteenth': 'Juneteenth',
    'Día de la Independencia': 'Independence',
    'Ramadán': 'RamadanStarts',
    'Eid al-Fitr': 'RamadanEnds',
    'Día del Trabajo': 'Labour',
    'Rosh Hashaná': 'JewNewYear',
    'Yom Kipur': 'YomKipur',
    'Día de Colón': 'Columbus',
    'Diwali': 'Hindu',
    'Día de los Veteranos': 'Veterans',
    'Día de Acción de Gracias': 'Thanksgiving',
    'Navidad': 'Christmas'
}

df['Nombre festivo'] = df['Nombre festivo'].replace(nombres_nuevos)

In [9]:
nombres_grupo = {
    'Nacional': 'national', 
    'Chino': 'chinese', 
    'Budismo': 'buddhist', 
    'Islam': 'islam', 
    'Judaísmo': 'jew', 
    'Hinduismo': 'hindu'
}

df['Grupo'] = df['Grupo'].replace(nombres_grupo)

In [10]:
df.head(25)

,Fecha,Nombre festivo,Grupo,Descripción
0,2011-01-01,NewYear,national,Celebración del primer día del año según el ca...
1,2011-01-17,MartinLutherKing,national,Honra al líder de los derechos civiles Martin ...
2,2011-02-03,ChineeseNewYear,chinese,Año Nuevo Chino
3,2011-02-06,Superbowl,national,Final del campeonato de la NFL
4,2011-02-21,President,national,Reconocimiento a todos los presidentes de EE.UU.
5,2011-03-17,StPatrick,national,"Fiesta en honor a San Patricio, patrón de Irla..."
6,2011-04-18,Memorial,national,Honra a los militares estadounidenses fallecid...
7,2011-05-17,Buddhist,buddhist,"Celebración budista del nacimiento, iluminació..."
8,2011-06-19,Juneteenth,national,Conmemoración del fin de la esclavitud en EE.U...
9,2011-07-04,Independence,national,Conmemoración de la independencia de EE.UU. en...
10,2011-08-01,RamadanStarts,islam,Mes sagrado de ayuno y oración para los musulm...
11,2011-08-30,RamadanEnds,islam,Fiesta que marca el fin del Ramadán en el islam.
12,2011-09-05,Labour,national,Reconocimiento a los trabajadores y sus contri...
13,2011-09-29,JewNewYear,jew,"Año Nuevo judío, marcado por oración y reflexión."
14,2011-10-08,YomKipur,jew,"Día del Perdón en el judaísmo, dedicado al ayu..."
15,2011-10-10,Columbus,national,Conmemoración de la llegada de Cristóbal Colón...
16,2011-10-26,Hindu,hindu,"Festival hindú de las luces, que simboliza la ..."
17,2011-11-11,Veterans,national,Honra a los veteranos de las Fuerzas Armadas d...
18,2011-11-24,Thanksgiving,national,Día de agradecimiento por la cosecha y bendici...
19,2011-12-25,Christmas,national,Fiesta cristiana que celebra el nacimiento de ...
20,2012-01-01,NewYear,national,Celebración del primer día del año según el ca...
21,2012-01-16,MartinLutherKing,national,Honra al líder de los derechos civiles Martin ...
22,2012-01-23,ChineeseNewYear,chinese,Año Nuevo Chino
23,2012-02-05,Superbowl,national,Final del campeonato de la NFL
24,2012-02-20,President,national,Reconocimiento a todos los presidentes de EE.UU.

In [11]:
# Creamos yearweek para usarlo como key en el merge

df['yearweek'] = df['Fecha'].dt.isocalendar().year.astype(str) + \
df['Fecha'].dt.isocalendar().week.astype(str).str.zfill(2)

In [12]:
df.head(20)

,Fecha,Nombre festivo,Grupo,Descripción,yearweek
0,2011-01-01,NewYear,national,Celebración del primer día del año según el ca...,201052
1,2011-01-17,MartinLutherKing,national,Honra al líder de los derechos civiles Martin ...,201103
2,2011-02-03,ChineeseNewYear,chinese,Año Nuevo Chino,201105
3,2011-02-06,Superbowl,national,Final del campeonato de la NFL,201105
4,2011-02-21,President,national,Reconocimiento a todos los presidentes de EE.UU.,201108
5,2011-03-17,StPatrick,national,"Fiesta en honor a San Patricio, patrón de Irla...",201111
6,2011-04-18,Memorial,national,Honra a los militares estadounidenses fallecid...,201116
7,2011-05-17,Buddhist,buddhist,"Celebración budista del nacimiento, iluminació...",201120
8,2011-06-19,Juneteenth,national,Conmemoración del fin de la esclavitud en EE.U...,201124
9,2011-07-04,Independence,national,Conmemoración de la independencia de EE.UU. en...,201127
10,2011-08-01,RamadanStarts,islam,Mes sagrado de ayuno y oración para los musulm...,201131
11,2011-08-30,RamadanEnds,islam,Fiesta que marca el fin del Ramadán en el islam.,201135
12,2011-09-05,Labour,national,Reconocimiento a los trabajadores y sus contri...,201136
13,2011-09-29,JewNewYear,jew,"Año Nuevo judío, marcado por oración y reflexión.",201139
14,2011-10-08,YomKipur,jew,"Día del Perdón en el judaísmo, dedicado al ayu...",201140
15,2011-10-10,Columbus,national,Conmemoración de la llegada de Cristóbal Colón...,201141
16,2011-10-26,Hindu,hindu,"Festival hindú de las luces, que simboliza la ...",201143
17,2011-11-11,Veterans,national,Honra a los veteranos de las Fuerzas Armadas d...,201145
18,2011-11-24,Thanksgiving,national,Día de agradecimiento por la cosecha y bendici...,201147
19,2011-12-25,Christmas,national,Fiesta cristiana que celebra el nacimiento de ...,201151

In [13]:
df[df['yearweek'].duplicated(keep=False)]

,Fecha,Nombre festivo,Grupo,Descripción,yearweek
2,2011-02-03,ChineeseNewYear,chinese,Año Nuevo Chino,201105
3,2011-02-06,Superbowl,national,Final del campeonato de la NFL,201105
52,2013-09-02,Labour,national,Reconocimiento a los trabajadores y sus contri...,201336
53,2013-09-05,JewNewYear,jew,"Año Nuevo judío, marcado por oración y reflexión.",201336
62,2014-01-31,ChineeseNewYear,chinese,Año Nuevo Chino,201405
63,2014-02-02,Superbowl,national,Final del campeonato de la NFL,201405
83,2015-02-16,President,national,Reconocimiento a todos los presidentes de EE.UU.,201508
84,2015-02-19,ChineeseNewYear,chinese,Año Nuevo Chino,201508
88,2015-06-18,RamadanStarts,islam,Mes sagrado de ayuno y oración para los musulm...,201525
89,2015-06-19,Juneteenth,national,Conmemoración del fin de la esclavitud en EE.U...,201525
96,2015-11-11,Veterans,national,Honra a los veteranos de las Fuerzas Armadas d...,201546
97,2015-11-11,Hindu,hindu,"Festival hindú de las luces, que simboliza la ...",201546
110,2016-07-04,Independence,national,Conmemoración de la independencia de EE.UU. en...,201627
111,2016-07-06,RamadanEnds,islam,Fiesta que marca el fin del Ramadán en el islam.,201627
114,2016-10-10,Columbus,national,Conmemoración de la llegada de Cristóbal Colón...,201641
115,2016-10-12,YomKipur,jew,"Día del Perdón en el judaísmo, dedicado al ayu...",201641

Como tenemos eventos que caen dentro de la misma semana, decidimos un enfoque de One Hot Encoding para no perder información

In [14]:
# Eliminamos las columnas que ya no usaremos
df.drop(['Fecha', 'Descripción'], axis=1, inplace=True)

In [15]:
# Cambiamos el nombre de las columnas para que sean los prefijos de las columnas OHE
df.rename(columns={'Nombre festivo': 'event', 'Grupo': 'event_group'}, inplace=True)

df_ohe = pd.get_dummies(df, columns = ['event','event_group'])

In [16]:
df_ohe.head()

,yearweek,event_Buddhist,event_ChineeseNewYear,event_Christmas,event_Columbus,event_Hindu,event_Independence,event_JewNewYear,event_Juneteenth,event_Labour,...,event_Superbowl,event_Thanksgiving,event_Veterans,event_YomKipur,event_group_buddhist,event_group_chinese,event_group_hindu,event_group_islam,event_group_jew,event_group_national
0,201052,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
1,201103,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
2,201105,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
3,201105,False,False,False,False,False,False,False,False,False,...,True,False,False,False,False,False,False,False,False,True
4,201108,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True

In [17]:
list(df_ohe.columns)

['yearweek',
 'event_Buddhist',
 'event_ChineeseNewYear',
 'event_Christmas',
 'event_Columbus',
 'event_Hindu',
 'event_Independence',
 'event_JewNewYear',
 'event_Juneteenth',
 'event_Labour',
 'event_MartinLutherKing',
 'event_Memorial',
 'event_NewYear',
 'event_President',
 'event_RamadanEnds',
 'event_RamadanStarts',
 'event_StPatrick',
 'event_Superbowl',
 'event_Thanksgiving',
 'event_Veterans',
 'event_YomKipur',
 'event_group_buddhist',
 'event_group_chinese',
 'event_group_hindu',
 'event_group_islam',
 'event_group_jew',
 'event_group_national']

In [18]:
# Creamos una columna extra que representará si hay evento en esa semana. Es True para todas las semanas de este df
df_ohe['has_event'] = True

In [19]:
# Codificamos con 1 y 0
for col in list(df_ohe.columns):
    df_ohe[col] = np.where(df_ohe[col] == True, 1, df_ohe[col])
    df_ohe[col] = np.where(df_ohe[col] == False, 0, df_ohe[col])

In [20]:
df_ohe

,yearweek,event_Buddhist,event_ChineeseNewYear,event_Christmas,event_Columbus,event_Hindu,event_Independence,event_JewNewYear,event_Juneteenth,event_Labour,...,event_Thanksgiving,event_Veterans,event_YomKipur,event_group_buddhist,event_group_chinese,event_group_hindu,event_group_islam,event_group_jew,event_group_national,has_event
0,201052,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,1
1,201103,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,1
2,201105,0,1,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,1
3,201105,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,1
4,201108,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,201641,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,1,0,1
116,201643,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,1,0,0,0,1
117,201645,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,1,1
118,201647,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,1,1
119,201651,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,1

In [21]:
# Comprobamos que hay varias filas con el mismo yearweek. Son semanas con más de un evento
df_ohe[df_ohe['yearweek'].duplicated(keep= False)]

,yearweek,event_Buddhist,event_ChineeseNewYear,event_Christmas,event_Columbus,event_Hindu,event_Independence,event_JewNewYear,event_Juneteenth,event_Labour,...,event_Thanksgiving,event_Veterans,event_YomKipur,event_group_buddhist,event_group_chinese,event_group_hindu,event_group_islam,event_group_jew,event_group_national,has_event
2,201105,0,1,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,1
3,201105,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,1
52,201336,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,1,1
53,201336,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,1,0,1
62,201405,0,1,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,1
63,201405,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,1
83,201508,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,1
84,201508,0,1,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,1
88,201525,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,1
89,201525,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,1
96,201546,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,1,1
97,201546,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,1,0,0,0,1
110,201627,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,1,1
111,201627,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,1
114,201641,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,1
115,201641,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,1,0,1

In [22]:
# Agrupamos las semanas con más de un evento en una única semana
df_ohe_agrupado = df_ohe.groupby('yearweek', as_index=False).max()

In [23]:
df_ohe_agrupado[df_ohe_agrupado['yearweek'].duplicated(keep= False)]

Empty DataFrame
Columns: [yearweek, event_Buddhist, event_ChineeseNewYear, event_Christmas, event_Columbus, event_Hindu, event_Independence, event_JewNewYear, event_Juneteenth, event_Labour, event_MartinLutherKing, event_Memorial, event_NewYear, event_President, event_RamadanEnds, event_RamadanStarts, event_StPatrick, event_Superbowl, event_Thanksgiving, event_Veterans, event_YomKipur, event_group_buddhist, event_group_chinese, event_group_hindu, event_group_islam, event_group_jew, event_group_national, has_event]
Index: []

[0 rows x 28 columns]

In [24]:
df_ohe_agrupado.to_csv('data/eventos_mejorados_ohe.csv')